blueprint:
  name: Critical Switch Warning (Multi-Switch)
  description: >
    Sends repeated critical notifications when one or more selected switches remain ON
    for a defined duration. Useful for pumps, fans, or other critical loads.
  domain: automation
  input:
    target_switches:
      name: Target Switches
      description: Select one or more switches to monitor.
      selector:
        entity:
          domain: switch
          multiple: true
    delay_minutes:
      name: Delay before first alert (minutes)
      description: How long the switches must stay ON before the first notification.
      default: 10
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
          mode: slider
    repeat_interval:
      name: Repeat interval (minutes)
      description: How often to resend notifications while any selected switch remains ON.
      default: 10
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
          mode: slider
    notify_device:
      name: Notification Device
      description: Select your iPhone (mobile_app).
      selector:
        device:
          integration: mobile_app
    message:
      name: Notification Message
      description: The message sent each time.
      default: "⚠️ Critical Alert: One or more switches have been ON for over {{ delay_mins }} minutes. Please check immediately."
      selector:
        text:

mode: restart

trigger:
  - platform: state
    entity_id: !input target_switches
    to: "on"
    for:
      minutes: !input delay_minutes

condition: []

action:
  # Expose blueprint inputs as plain variables (so we can use them in templates)
  - variables:
      monitored_switches: !input target_switches
      delay_mins: !input delay_minutes
      repeat_mins: !input repeat_interval
      user_message: !input message

  - repeat:
      while:
        - condition: template
          value_template: >
            {{ expand(monitored_switches)
               | selectattr('state', 'eq', 'on')
               | list | length > 0 }}
      sequence:
        # Recompute which switches are ON each loop
        - variables:
            switches_on: >
              {{ expand(monitored_switches)
                 | selectattr('state', 'eq', 'on')
                 | map(attribute='name') | list }}

        # Send to your chosen mobile_app device (e.g., notify.mobile_app_msharys_iphone_14_pro)
        - device_id: !input notify_device
          domain: mobile_app
          type: notify
          title: "Critical Switch Warning"
          message: >
            {{ user_message }}
            {% if switches_on|length > 0 %}
            Affected: {{ switches_on | join(', ') }}
            {% endif %}
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1

        - delay:
            minutes: "{{ repeat_mins }}"
