blueprint:
  name: Critical Switch Warning (Multi-Switch)
  description: >
    Sends repeated critical notifications when one or more selected switches remain ON
    for a defined duration. Useful for pumps, fans, or other critical loads.
  domain: automation
  input:
    target_switches:
      name: Target Switches
      description: Select one or more switches to monitor.
      selector:
        entity:
          multiple: true
          domain: switch
    delay_minutes:
      name: Delay before first alert (minutes)
      description: How long the switches must stay ON before the first notification.
      default: 10
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
          mode: slider
    repeat_interval:
      name: Repeat interval (minutes)
      description: How often to resend notifications while switches remain ON.
      default: 10
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
          mode: slider
    notify_device:
      name: Notification Device
      description: Select your mobile device to receive notifications.
      selector:
        device:
          integration: mobile_app
    message:
      name: Notification Message
      description: The message sent each time.
      default: "⚠️ Critical Alert: One or more switches have been ON for over {{ delay_minutes }} minutes. Please check immediately."
      selector:
        text:

mode: restart

trigger:
  - platform: state
    entity_id: !input target_switches
    to: "on"
    for:
      minutes: !input delay_minutes

condition: []

action:
  - variables:
      switches_on: >
        {{ expand(!input target_switches) | selectattr('state', 'eq', 'on') | map(attribute='name') | list }}
  - repeat:
      while:
        - condition: template
          value_template: >
            {{ expand(!input target_switches) | selectattr('state', 'eq', 'on') | list | count > 0 }}
      sequence:
        - device_id: !input notify_device
          domain: mobile_app
          type: notify
          message: >
            ⚠️ Critical Alert:
            The following switches have been ON for over {{ delay_minutes }} minutes:
            {{ switches_on | join(', ') }}
          title: "Critical Switch Warning"
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1
        - delay:
            minutes: !input repeat_interval
