blueprint:
  name: Temp & Motion-Aware Climate Control (Hysteresis)
  description: >
    Turns on the chosen climate entities in the specified HVAC mode when the
    temperature sensor rises above the high threshold—only if those climates are all off.
    When the temperature falls below the low threshold, it will
      1) if motion is detected, wait until motion stops,
      2) then wait the configured off-delay,
      3) finally turn off those same climate entities.
  domain: automation

  input:
    temperature_sensor:
      name: Temperature Sensor
      description: Sensor that measures ambient temperature.
      selector:
        entity:
          domain: sensor

    motion_sensor:
      name: Motion Sensor
      description: Prevents immediate shut-off while occupied.
      selector:
        entity:
          domain: binary_sensor

    climates_to_control:
      name: Climates to Control
      description: Climate entities to activate/deactivate based on temperature.
      selector:
        entity:
          domain: climate
          multiple: true

    hvac_mode:
      name: HVAC Mode
      description: Mode to set on your controlled climates when the temperature is high.
      default: cool
      selector:
        select:
          options:
            - heat
            - cool
            - auto
            - fan_only
            - dry

    low_temperature_threshold:
      name: Low Temperature Threshold
      description: "Temperature (°C) below which climates turn off."
      default: 22
      selector:
        number:
          unit_of_measurement: °C
          min: -50
          max: 50

    high_temperature_threshold:
      name: High Temperature Threshold
      description: "Temperature (°C) above which climates turn on."
      default: 25
      selector:
        number:
          unit_of_measurement: °C
          min: -50
          max: 50

    wait_time:
      name: Wait Time
      description: "Seconds to wait after motion stops (if any) before turning off the climates once the temperature is below low threshold."
      default: 300
      selector:
        number:
          unit_of_measurement: seconds
          min: 0
          max: 3600

trigger:
  - id: temp_high
    platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input high_temperature_threshold

  - id: temp_low
    platform: numeric_state
    entity_id: !input temperature_sensor
    below: !input low_temperature_threshold

action:
  - choose:
      - conditions:
          - condition: trigger
            id: temp_high
        sequence:
          # Only turn on if all controlled climates are currently off
          - condition: state
            entity_id: !input climates_to_control
            state: "off"

          # Activate in the chosen HVAC mode
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climates_to_control
            data:
              hvac_mode: !input hvac_mode

      - conditions:
          - condition: trigger
            id: temp_low
        sequence:
          # If motion is active, wait for it to stop
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input motion_sensor
                    state: "on"
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensor
                        to: "off"

          # Then wait the off-delay
          - delay:
              seconds: !input wait_time

          # Finally, turn off the controlled climates
          - service: climate.turn_off
            target:
              entity_id: !input climates_to_control

mode: restart
